[package]
name = "collapse_updater"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
reqwest = { version = "0.13.1", features = ["json", "stream"] }
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.49.0", features = ["full"] }
indicatif = "0.18.3"
futures = "0.3.31"
console = "0.16.2"
directories = "6.0.0"
anyhow = "1.0.100"
sys-locale = "0.3.2"

[build-dependencies]
winres = "0.1.12"

[profile.release]
codegen-units = 1
opt-level = "z"
panic = "abort"
strip = true
lto = true
